[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
aion = "Aiondoc3kxg6Yekk87CUnCVsNoj5wJJvCBdybWk75RHK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://intensive-dry-firefly.solana-mainnet.quiknode.pro/3d4155f04d65fcf2492ab4649f24ac6f10785117"
wallet = "/home/aion/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"

[workspace]
types = "target/types/"
members = ["programs/aion"]


